services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: api_concerts_pictures
    ports:
      - "3000:3000"
    environment:
      - MONGODB_SERVICE=${ME_CONFIG_MONGODB_SERVER}
      - MONGODB_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGODB_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGODB_PORT=27017
    depends_on:
      - mongodb
    networks:
      - backend-net-pictures

  mongodb:
    image: mongo:7
    container_name: mongo_db_pictures
    ports: 
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-net-pictures

  mongo-express:
    image: mongo-express
    container_name: mongo_express_pictures
    ports:
      - "8082:8082"
    environment:
      - ME_CONFIG_MONGODB_SERVER=${ME_CONFIG_MONGODB_SERVER}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${ME_CONFIG_MONGODB_ADMINUSERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${ME_CONFIG_MONGODB_ADMINPASSWORD}
      - ME_CONFIG_MONGODB_AUTH_DATABASE=${ME_CONFIG_MONGODB_AUTH_DATABASE}
    depends_on:
      - mongodb
    networks:
      - backend-net-pictures

volumes:
  mongo-data:

networks:
  backend-net-pictures:
    driver: bridge
